# Generated by Django 5.1.6 on 2025-03-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.IntegerField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dateofbirth', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('enrollementdate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
