# Generated by Django 5.1.6 on 2025-03-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='enrollementdate',
            new_name='enrollmentdate',
        ),
    ]
